theme: jekyll-theme-slate

title: ALPhA Davidson
description: Algorithms for Learning in Physics Applications
logo: /assets/images/logo.png
show_downloads: true
github:
  repository_url: https://github.com/alpha-davidson
google_analytics: UA-164678666-1

