theme: jekyll-theme-slate

title: ALPhA Davidson
description: Algorithms for Learning in Physics Applications research group at Davidson College.
show_downloads: true
github:
  repository_url: https://github.com/alpha-davidson
